import {StyleSheet} from 'react-native';
import {fontStyle} from '../../globals/fonts';

export const createManageAssetsStyles = theme =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    keyboardAvoider: {
      flex: 1,
    },
    scrollFrame: {
      flex: 1,
      minHeight: 0,
    },
    scroll: {
      flex: 1,
    },
    overviewContent: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 28,
    },
    overviewContentCompact: {
      paddingTop: 10,
      paddingBottom: 20,
    },
    walletCard: {
      minHeight: 64,
      marginTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: theme.colors.surfaceMuted,
    },
    walletLogos: {
      minWidth: 70,
      flexDirection: 'row',
      alignItems: 'center',
    },
    overlappingLogo: {
      width: 30,
      height: 30,
      alignItems: 'center',
      justifyContent: 'center',
    },
    overlappingLogoAfterFirst: {
      marginLeft: -8,
    },
    walletCopy: {
      flex: 1,
      minWidth: 0,
      marginLeft: 10,
    },
    walletTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 19,
      ...fontStyle('semiBold'),
    },
    walletDescription: {
      marginTop: 1,
      color: theme.colors.textSubtle,
      fontSize: 12,
      lineHeight: 17,
      ...fontStyle('regular'),
    },
    walletAction: {
      marginLeft: 8,
      color: theme.colors.primary,
      fontSize: 14,
      lineHeight: 19,
      ...fontStyle('semiBold'),
    },
    sectionTitle: {
      marginTop: 20,
      marginBottom: 12,
      color: theme.colors.textPrimary,
      fontSize: 17,
      lineHeight: 23,
      letterSpacing: -0.15,
      ...fontStyle('semiBold'),
    },
    sectionTitleCompact: {
      marginTop: 14,
      marginBottom: 9,
    },
    ecosystemCard: {
      minHeight: 118,
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 20,
      padding: 16,
      backgroundColor: theme.isDark ? theme.colors.surfaceMuted : '#EAF0FC',
    },
    ecosystemCardCompact: {
      minHeight: 108,
      paddingVertical: 13,
    },
    ecosystemCopy: {
      flex: 1,
      minWidth: 0,
      paddingRight: 10,
    },
    ecosystemTitle: {
      color: theme.colors.textPrimary,
      fontSize: 17,
      lineHeight: 23,
      ...fontStyle('semiBold'),
    },
    ecosystemDescription: {
      maxWidth: 220,
      marginTop: 7,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 19,
      ...fontStyle('regular'),
    },
    ecosystemAction: {
      marginTop: 7,
      color: theme.colors.primary,
      fontSize: 12,
      lineHeight: 17,
      ...fontStyle('semiBold'),
    },
    logoStack: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
    logoTile: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      backgroundColor: '#FFFFFF',
      shadowColor: '#111827',
      shadowOpacity: 0.08,
      shadowRadius: 7,
      shadowOffset: {width: 0, height: 2},
      elevation: 2,
    },
    logoTileSmall: {
      width: 34,
      height: 34,
      borderRadius: 10,
    },
    logoTileAfterFirst: {
      marginLeft: -8,
    },
    categoryRow: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 12,
    },
    categoryCard: {
      flex: 1,
      minWidth: 0,
      minHeight: 104,
      borderRadius: 18,
      padding: 14,
    },
    categoryCardCompact: {
      minHeight: 96,
      paddingVertical: 12,
    },
    blockchainCard: {
      backgroundColor: theme.isDark ? '#2A211C' : '#FFF4E8',
    },
    bridgeCard: {
      backgroundColor: theme.isDark ? '#211E35' : '#F0EEFB',
    },
    categoryTitle: {
      marginTop: 11,
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 19,
      ...fontStyle('semiBold'),
    },
    categoryDescription: {
      marginTop: 2,
      color: theme.colors.textSecondary,
      fontSize: 11,
      lineHeight: 15,
      ...fontStyle('regular'),
    },
    popularHeader: {
      marginTop: 20,
      flexDirection: 'row',
      alignItems: 'flex-end',
    },
    popularCopy: {
      flex: 1,
      minWidth: 0,
    },
    popularTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 19,
      ...fontStyle('semiBold'),
    },
    popularDescription: {
      marginTop: 1,
      color: theme.colors.textSubtle,
      fontSize: 12,
      lineHeight: 17,
      ...fontStyle('regular'),
    },
    viewAll: {
      marginLeft: 12,
      paddingVertical: 6,
      color: theme.colors.primary,
      fontSize: 14,
      lineHeight: 19,
      ...fontStyle('semiBold'),
    },
    assetRows: {
      marginTop: 6,
    },
    assetRow: {
      minHeight: 70,
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
      paddingVertical: 10,
    },
    rowLogo: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    rowCopy: {
      flex: 1,
      minWidth: 0,
      paddingRight: 8,
    },
    rowTitleLine: {
      flexDirection: 'row',
      alignItems: 'baseline',
    },
    rowName: {
      flexShrink: 1,
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 20,
      ...fontStyle('semiBold'),
    },
    rowTicker: {
      flexShrink: 0,
      marginLeft: 7,
      color: theme.colors.textSubtle,
      fontSize: 12,
      lineHeight: 17,
      ...fontStyle('medium'),
    },
    rowDescription: {
      marginTop: 4,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      ...fontStyle('regular'),
    },
    rowButton: {
      minWidth: 70,
    },
    rowButtonLabel: {
      marginHorizontal: 8,
      fontSize: 12,
      lineHeight: 16,
      ...fontStyle('semiBold'),
    },
    footer: {
      paddingTop: 10,
      backgroundColor: theme.colors.background,
    },
    footerButton: {
      width: '100%',
    },
    scrollCue: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: 46,
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    scrollCueFade: {
      ...StyleSheet.absoluteFillObject,
    },
    scrollCueChevron: {
      height: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    directoryHeader: {
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 10,
      backgroundColor: theme.colors.background,
    },
    filters: {
      marginTop: 10,
    },
    filtersContent: {
      gap: 6,
      paddingRight: 12,
    },
    filterButton: {
      minWidth: 58,
    },
    filterLabel: {
      marginHorizontal: 8,
      fontSize: 12,
      lineHeight: 16,
      ...fontStyle('semiBold'),
    },
    walletHelper: {
      marginTop: 10,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 9,
      backgroundColor: theme.colors.surfaceMuted,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    directoryMeta: {
      minHeight: 30,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
    },
    resultCount: {
      color: theme.colors.textSubtle,
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      ...fontStyle('bold'),
    },
    activeCount: {
      color: theme.colors.textSubtle,
      fontSize: 12,
      lineHeight: 17,
      ...fontStyle('medium'),
    },
    directoryList: {
      paddingHorizontal: 20,
      paddingBottom: 24,
    },
    directoryListEmpty: {
      flexGrow: 1,
    },
    empty: {
      flex: 1,
      minHeight: 190,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 28,
    },
    emptyTitle: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 22,
      textAlign: 'center',
      ...fontStyle('semiBold'),
    },
    emptyDescription: {
      marginTop: 5,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
      ...fontStyle('regular'),
    },
    errorBanner: {
      marginHorizontal: 20,
      marginBottom: 8,
      flexDirection: 'row',
      alignItems: 'flex-start',
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: theme.isDark ? 'rgba(255, 107, 117, 0.16)' : '#FFF0F1',
    },
    overviewErrorBanner: {
      marginHorizontal: 0,
    },
    errorText: {
      flex: 1,
      marginLeft: 8,
      color: theme.colors.danger,
      fontSize: 12,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    identifierContent: {
      flexGrow: 1,
      paddingHorizontal: 20,
      paddingTop: 18,
      paddingBottom: 20,
    },
    identifierContentCompact: {
      paddingTop: 10,
      paddingBottom: 14,
    },
    identifierIntro: {
      paddingBottom: 18,
    },
    identifierTitle: {
      color: theme.colors.textPrimary,
      fontSize: 22,
      lineHeight: 29,
      letterSpacing: -0.25,
      ...fontStyle('semiBold'),
    },
    identifierDescription: {
      marginTop: 7,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 21,
      ...fontStyle('regular'),
    },
    identifierFieldGroup: {
      gap: 7,
    },
    identifierFieldLabel: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('semiBold'),
    },
    identifierInput: {
      minHeight: 96,
      maxHeight: 132,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingTop: 13,
      paddingBottom: 13,
      backgroundColor: theme.colors.input,
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 21,
      ...fontStyle('regular'),
    },
    identifierInputError: {
      borderColor: theme.colors.danger,
    },
    identifierInlineError: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: theme.isDark
        ? 'rgba(255, 107, 117, 0.16)'
        : '#FFF0F1',
    },
    identifierInlineErrorText: {
      flex: 1,
      marginLeft: 8,
      color: theme.colors.danger,
      fontSize: 12,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    identifierDetected: {
      marginTop: 16,
      flexDirection: 'row',
      alignItems: 'flex-start',
      borderRadius: 16,
      padding: 14,
      backgroundColor: theme.colors.surfaceMuted,
    },
    identifierDetectedIcon: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 10,
      backgroundColor: theme.colors.background,
    },
    identifierDetectedCopy: {
      flex: 1,
      minWidth: 0,
      marginLeft: 12,
    },
    identifierDetectedEyebrow: {
      color: theme.colors.textSubtle,
      fontSize: 10,
      lineHeight: 14,
      letterSpacing: 0.7,
      textTransform: 'uppercase',
      ...fontStyle('bold'),
    },
    identifierDetectedTitle: {
      marginTop: 2,
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 20,
      ...fontStyle('semiBold'),
    },
    identifierDetectedDescription: {
      marginTop: 3,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    identifierFooter: {
      paddingTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.border,
      backgroundColor: theme.colors.background,
    },
    identifierReviewIntro: {
      marginBottom: 16,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 21,
      ...fontStyle('regular'),
    },
    identifierReviewHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 14,
    },
    identifierReviewIcon: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
      backgroundColor: theme.colors.surfaceMuted,
    },
    identifierReviewHeaderCopy: {
      flex: 1,
      minWidth: 0,
      marginLeft: 13,
    },
    identifierReviewName: {
      color: theme.colors.textPrimary,
      fontSize: 19,
      lineHeight: 25,
      ...fontStyle('semiBold'),
    },
    identifierReviewTicker: {
      marginTop: 2,
      color: theme.colors.textSubtle,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('medium'),
    },
    identifierReviewCard: {
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 18,
      paddingHorizontal: 15,
      backgroundColor: theme.colors.surface,
    },
    identifierReviewRow: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
      paddingVertical: 12,
    },
    identifierReviewLabel: {
      color: theme.colors.textSubtle,
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.45,
      textTransform: 'uppercase',
      ...fontStyle('bold'),
    },
    identifierReviewValue: {
      marginTop: 3,
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('medium'),
    },
    identifierCallout: {
      marginTop: 14,
      flexDirection: 'row',
      alignItems: 'flex-start',
      borderRadius: 14,
      padding: 13,
    },
    identifierCalloutTrusted: {
      backgroundColor: theme.colors.successBackground,
    },
    identifierCalloutWarning: {
      backgroundColor: theme.isDark
        ? 'rgba(255, 178, 92, 0.14)'
        : '#FFF6EA',
    },
    identifierCalloutInfo: {
      backgroundColor: theme.colors.surfaceMuted,
    },
    identifierCalloutCopy: {
      flex: 1,
      minWidth: 0,
      marginLeft: 10,
    },
    identifierCalloutTitle: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('semiBold'),
    },
    identifierCalloutDescription: {
      marginTop: 3,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    identifierAdding: {
      alignItems: 'center',
      marginBottom: 18,
      borderRadius: 16,
      padding: 16,
      backgroundColor: theme.colors.surfaceMuted,
    },
    identifierAddingTitle: {
      marginTop: 9,
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 20,
      ...fontStyle('semiBold'),
    },
    identifierAddingDescription: {
      marginTop: 3,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      textAlign: 'center',
      ...fontStyle('regular'),
    },
    identifierSuccess: {
      flex: 1,
      minHeight: 310,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 22,
    },
    identifierSuccessIcon: {
      width: 76,
      height: 76,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 24,
      backgroundColor: theme.colors.successBackground,
    },
    identifierSuccessTitle: {
      marginTop: 18,
      color: theme.colors.textPrimary,
      fontSize: 23,
      lineHeight: 30,
      textAlign: 'center',
      ...fontStyle('semiBold'),
    },
    identifierSuccessDescription: {
      marginTop: 7,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 21,
      textAlign: 'center',
      ...fontStyle('regular'),
    },
  });
