import {Platform, StyleSheet} from 'react-native';

export const createManageAssetsStyles = theme => StyleSheet.create({
  screen: {flex: 1, backgroundColor: theme.colors.background},
  keyboardAvoider: {flex: 1},
  headerContent: {paddingHorizontal: 20},
  scrollFrame: {flex: 1, minHeight: 0},
  scroll: {flex: 1},
  listContent: {paddingHorizontal: 20, paddingBottom: 24},
  filters: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 56, gap: 8},
  tabs: {flexDirection: 'row', alignItems: 'center', gap: 16},
  tab: {minHeight: 44, justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent'},
  tabSelected: {borderBottomColor: theme.colors.primary},
  tabLabel: {...theme.typography.bodySm, color: theme.colors.textSecondary},
  tabLabelSelected: {...theme.typography.labelMd, color: theme.colors.textPrimary},
  networkFilter: {minHeight: 44, flexDirection: 'row', alignItems: 'center', flexShrink: 1, gap: 3},
  networkFilterLabel: {...theme.typography.caption, color: theme.colors.textSecondary, flexShrink: 1},
  sectionHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 18, paddingBottom: 4, gap: 8},
  sectionLabel: {...theme.typography.labelMd, color: theme.colors.textSecondary},
  sectionDetail: {...theme.typography.caption, color: theme.colors.textSecondary},
  assetRow: {minHeight: 76, flexDirection: 'row', alignItems: 'center', paddingVertical: 12, gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border},
  rowLogo: {width: 40, height: 40, flexShrink: 0, alignItems: 'center', justifyContent: 'center'},
  unknownLogo: {width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.surfaceMuted},
  unknownLabel: {...theme.typography.titleSheet, color: theme.colors.textSecondary},
  rowCopy: {flex: 1, minWidth: 0, gap: 2},
  rowName: {...theme.typography.titleRow, color: theme.colors.textPrimary},
  rowDescription: {...theme.typography.bodySm, color: theme.colors.textSecondary},
  rowAction: {width: 66, minHeight: 44, flexShrink: 0, justifyContent: 'center', alignItems: 'flex-end'},
  switchAction: {width: 52, minHeight: 44, flexShrink: 0, justifyContent: 'center', alignItems: 'center'},
  actionLabel: {...theme.typography.labelMd, color: theme.colors.primary},
  addedLabel: {...theme.typography.bodySm, color: theme.colors.textSecondary},
  footer: {paddingTop: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border, backgroundColor: theme.colors.background},
  customEntry: {minHeight: 80, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border},
  customEntryCopy: {flex: 1, minWidth: 0, gap: 4},
  helper: {...theme.typography.bodySm, color: theme.colors.textSecondary, marginTop: 20},
  empty: {paddingVertical: 32, gap: 8},
  emptyTitle: {...theme.typography.titleRow, color: theme.colors.textPrimary},
  error: {marginHorizontal: 20, marginBottom: 12, padding: 16, borderRadius: theme.rounded.md, backgroundColor: theme.colors.surfaceMuted, gap: 8},
  errorText: {...theme.typography.bodySm, color: theme.colors.textSecondary},
  scrollCue: {position: 'absolute', bottom: 0, left: 0, right: 0, height: 46, justifyContent: 'flex-end', alignItems: 'center'},
  scrollCueFade: {position: 'absolute', left: 0, right: 0, bottom: 0},
  scrollCueChevron: {height: 20, alignItems: 'center', justifyContent: 'center'},
  segment: {flexDirection: 'row', padding: 4, gap: 4, borderRadius: theme.rounded.md, backgroundColor: theme.colors.surfaceMuted},
  segmentOption: {flex: 1, minHeight: 44, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 8, borderRadius: 9},
  segmentSelected: {backgroundColor: theme.colors.surface},
  formContent: {paddingTop: 28},
  fieldGroup: {gap: 8, marginBottom: 24},
  fieldLabel: {...theme.typography.labelMd, color: theme.colors.textSecondary},
  networkInput: {minHeight: 56, borderWidth: 1, borderColor: theme.colors.borderStrong, backgroundColor: theme.colors.input, borderRadius: theme.rounded.md, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 16, paddingVertical: 14},
  fieldValue: {...theme.typography.bodyMd, color: theme.colors.textPrimary, flex: 1},
  inputShell: {borderColor: theme.colors.borderStrong},
  input: {...theme.typography.bodyMd},
  formHelper: {...theme.typography.bodySm, color: theme.colors.textSecondary},
  lookupError: {padding: 16, gap: 8, borderRadius: theme.rounded.md, backgroundColor: theme.colors.surfaceMuted, marginTop: 20},
  reviewHeader: {flexDirection: 'row', alignItems: 'center', gap: 12, paddingTop: 12, paddingBottom: 24},
  reviewName: {...theme.typography.titleSheet, color: theme.colors.textPrimary},
  reviewBalance: {backgroundColor: theme.colors.surfaceMuted, borderRadius: theme.rounded.md, padding: 16, gap: 6},
  reviewAmount: {...theme.typography.headlineMd, color: theme.colors.textPrimary},
  reviewRow: {paddingVertical: 16, gap: 5, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border},
  reviewValueLine: {flexDirection: 'row', alignItems: 'center', gap: 8},
  reviewValue: {...theme.typography.bodyMd, color: theme.colors.textPrimary, flex: 1},
  identifier: {fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', fontSize: 14},
  reviewCopy: {...theme.typography.bodySm, color: theme.colors.textSecondary, marginTop: 24},
  reviewHomeCopy: {...theme.typography.bodySm, color: theme.colors.textSecondary, marginTop: 16},
  sheetTitle: {...theme.typography.titleSheet, color: theme.colors.textPrimary, marginBottom: 20},
  networkOption: {minHeight: 56, marginVertical: 4, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 18, backgroundColor: theme.colors.surfaceMuted, flexDirection: 'row', alignItems: 'center', gap: 8},
  networkOptionSelected: {backgroundColor: theme.colors.successBackground},
  networkOptionLabel: {...theme.typography.titleRow, color: theme.colors.textPrimary, flex: 1},
  skeletonRow: {height: 76, flexDirection: 'row', alignItems: 'center', gap: 12},
});
