const signedInCopy = {
  navigation: {
    wallet: 'Wallet',
    services: 'Services',
    identity: 'VerusID',
    settings: 'Settings',
    scan: 'Scan',
  },
  actions: {
    receive: 'Receive',
    send: 'Send',
    convert: 'Convert',
    manageAssets: 'Manage assets',
    retry: 'Try again',
    refresh: 'Refresh',
  },
  wallet: {
    title: 'Wallet',
    portfolio: 'Portfolio balance',
    assets: 'Assets',
    priceUnavailable: 'Price unavailable',
    noAssets: 'No assets enabled',
    noAssetsDescription: 'Add an asset to start using your wallet.',
    selectSource: 'Select an Asset and Card',
  },
  settings: {
    title: 'Settings',
    securityAndRecovery: 'Security & recovery',
    walletAndSecurity: 'Wallet and security',
    general: 'General',
    appearance: 'Appearance',
    networkAndStorage: 'Network & storage',
    appInformation: 'App information',
    appearanceDescription: 'Choose how Verus Mobile looks on this device.',
    system: 'System',
    systemDescription: 'Follow your device appearance',
    light: 'Light',
    lightDescription: 'Always use the light appearance',
    dark: 'Dark',
    darkDescription: 'Always use the dark appearance',
  },
  services: {
    title: 'Services',
    description: 'Wallet capabilities you can choose to use.',
    giftCards: 'Gift Cards',
    addressBook: 'Address Book',
    verusIdSetup: 'VerusID setup',
  },
  identity: {
    title: 'Identity',
    description: 'Link and manage VerusIDs controlled by this wallet.',
  },
};

export default signedInCopy;
