/*
  AuthenticationRequestInfo.styles
  - Theme-aware flat layout styles for the authentication request screen.
*/
import {Platform, StyleSheet} from 'react-native';
import {fontStyle} from '../../globals/fonts';

const createAuthenticationRequestInfoStyles = theme =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.md,
      paddingBottom: theme.spacing.xl,
    },
    header: {
      marginBottom: 28,
    },
    mainTitle: {
      color: theme.colors.textPrimary,
      letterSpacing: 0,
      ...theme.typography.headlineLg,
    },
    requesterCard: {
      marginBottom: theme.spacing.xl,
    },
    requesterIdentityPanel: {
      minHeight: 64,
      borderRadius: 14,
      backgroundColor: theme.colors.surfaceMuted,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: 15,
      flexDirection: 'row',
      alignItems: 'center',
    },
    requesterTextContainer: {
      flex: 1,
      minWidth: 0,
    },
    requesterLabel: {
      color: theme.colors.textSubtle,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0,
      marginBottom: 8,
      ...fontStyle('semiBold'),
    },
    requesterName: {
      color: theme.colors.textPrimary,
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
      ...fontStyle('semiBold'),
    },
    requesterDetailsList: {
      marginTop: theme.spacing.sm,
    },
    requesterDetailRow: {
      minWidth: 0,
      minHeight: 45,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    requesterDetailRowDivider: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.border,
    },
    requesterDetailLabel: {
      color: theme.colors.textSubtle,
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0,
      ...fontStyle('regular'),
    },
    requesterDetailValue: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0,
      textAlign: 'right',
      ...fontStyle('semiBold'),
    },
    requestDetailsLinkTouch: {
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'flex-start',
      marginTop: theme.spacing.sm,
    },
    requestDetailsLinkText: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 22,
      letterSpacing: 0,
      ...fontStyle('semiBold'),
    },
    sectionCard: {
      marginBottom: theme.spacing.lg,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      minHeight: 44,
      paddingVertical: theme.spacing.xs,
    },
    sectionHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
      minWidth: 0,
    },
    sectionTitle: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 22,
      letterSpacing: 0,
      ...fontStyle('semiBold'),
    },
    sectionContent: {
      paddingTop: theme.spacing.xs,
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      paddingVertical: 10,
    },
    detailRowBorder: {},
    detailLeft: {
      flex: 1,
      minWidth: 0,
    },
    detailTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      marginBottom: 2,
      ...fontStyle('regular'),
    },
    detailSubtitle: {
      color: theme.colors.textSubtle,
      fontSize: 12,
      lineHeight: 17,
      letterSpacing: 0,
      ...fontStyle('regular'),
    },
    requirementLabel: {
      flex: 1,
      marginRight: 12,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      ...fontStyle('regular'),
    },
    requirementValue: {
      flexShrink: 1,
      maxWidth: '55%',
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      textAlign: 'right',
      ...fontStyle('semiBold'),
    },
    simpleInfoRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      paddingVertical: theme.spacing.xs,
      marginBottom: theme.spacing.sm,
    },
    simpleInfoText: {
      flex: 1,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      ...fontStyle('regular'),
    },
    footer: {
      backgroundColor: theme.colors.background,
      paddingTop: theme.spacing.sm,
    },
    footerInfoRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      marginBottom: theme.spacing.xs,
    },
    footerInfoIcon: {
      width: 16,
      height: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    footerInfoText: {
      flex: 1,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      ...fontStyle('regular'),
    },
    selectedIdentityLabel: {
      color: theme.colors.textSubtle,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0,
      marginBottom: 8,
      ...fontStyle('semiBold'),
    },
    selectedIdentityCard: {
      minHeight: 76,
      borderRadius: 18,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: 14,
      backgroundColor: theme.colors.successBackground,
      flexDirection: 'row',
      alignItems: 'center',
    },
    selectedIdentityText: {
      flex: 1,
      minWidth: 0,
      paddingRight: 10,
    },
    selectedIdentityName: {
      color: theme.colors.textPrimary,
      fontSize: 17,
      lineHeight: 22,
      letterSpacing: 0,
      ...fontStyle('semiBold'),
    },
    selectedIdentityAddress: {
      marginTop: 5,
      color: theme.colors.textSubtle,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0,
      fontFamily: Platform.select({
        ios: 'Menlo',
        android: 'monospace',
        default: 'monospace',
      }),
    },
    selectedIdentityCheck: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 2,
    },
    requestDetailsSheetBody: {
      paddingHorizontal: theme.spacing.sheetPadding,
      paddingTop: theme.spacing.sm,
      paddingBottom: 22,
    },
    requestDetailsSheetTitle: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      lineHeight: 26,
      letterSpacing: 0,
      ...fontStyle('semiBold'),
    },
    requestDetailsSheetContent: {
      paddingTop: theme.spacing.md,
      paddingBottom: theme.spacing.xs,
    },
    requestDetailsSection: {
      marginBottom: theme.spacing.lg,
    },
    requestDetailsSectionTitle: {
      color: theme.colors.textSubtle,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0,
      marginBottom: theme.spacing.xs,
      ...fontStyle('semiBold'),
    },
    requestDetailsRow: {
      paddingVertical: 9,
    },
    requestDetailsLabel: {
      color: theme.colors.textSubtle,
      fontSize: 12,
      lineHeight: 17,
      letterSpacing: 0,
      marginBottom: 3,
      ...fontStyle('semiBold'),
    },
    requestDetailsValue: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 21,
      letterSpacing: 0,
      ...fontStyle('regular'),
    },
  });

export default createAuthenticationRequestInfoStyles;
