import {StyleSheet} from 'react-native';
import {fontStyle} from '../../globals/fonts';

const createSpendableKeyRequestInfoStyles = theme =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scrollContent: {
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.md,
      paddingBottom: theme.spacing.md,
    },
    scrollEndSpacer: {
      height: theme.spacing.sm,
    },
    header: {
      marginBottom: theme.spacing.lg,
    },
    mainTitle: {
      color: theme.colors.textPrimary,
      letterSpacing: 0,
      ...theme.typography.headlineLg,
    },
    subtitle: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      marginTop: 10,
      ...fontStyle('regular'),
    },
    centerContent: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: theme.spacing.xl,
    },
    loadingText: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      lineHeight: 24,
      letterSpacing: 0,
      marginTop: theme.spacing.md,
      textAlign: 'center',
      ...fontStyle('semiBold'),
    },
    loadingDescription: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      marginTop: theme.spacing.sm,
      textAlign: 'center',
      ...fontStyle('regular'),
    },
    passwordScreen: {
      flex: 1,
    },
    passwordScrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      paddingHorizontal: theme.spacing.lg,
      paddingBottom: theme.spacing.lg,
    },
    passwordTitle: {
      color: theme.colors.textPrimary,
      letterSpacing: 0,
      textAlign: 'center',
      ...theme.typography.headlineMd,
    },
    passwordDescription: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
      marginBottom: theme.spacing.lg,
      marginTop: 10,
      textAlign: 'center',
      ...fontStyle('regular'),
    },
    passwordInput: {
      backgroundColor: theme.colors.input,
    },
    iconWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: theme.colors.surfaceMuted,
      marginBottom: theme.spacing.md,
    },
    scannerContainer: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    requestCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: theme.rounded.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceRaised,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.md,
    },
    requestCardIcon: {
      width: 46,
      height: 46,
      borderRadius: 23,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
      marginRight: 12,
    },
    requestCardText: {
      flex: 1,
      minWidth: 0,
    },
    requestCardLabel: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 22,
      letterSpacing: 0,
      ...fontStyle('semiBold'),
    },
    requestCardValue: {
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0,
      marginTop: 2,
      ...fontStyle('regular'),
    },
    summaryCard: {
      backgroundColor: theme.colors.surfaceRaised,
      borderRadius: theme.rounded.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.md,
    },
    summaryTitle: {
      fontSize: 15,
      lineHeight: 20,
      letterSpacing: 0,
      color: theme.colors.textPrimary,
      marginBottom: 12,
      ...fontStyle('semiBold'),
    },
    summaryRow: {
      flexDirection: 'row',
      gap: 12,
    },
    summaryItem: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceMuted,
      borderRadius: theme.rounded.md,
      paddingVertical: 12,
    },
    summaryCount: {
      fontSize: 24,
      lineHeight: 30,
      color: theme.colors.textPrimary,
      ...fontStyle('semiBold'),
    },
    summaryLabel: {
      fontSize: 12,
      lineHeight: 17,
      color: theme.colors.textSecondary,
      marginTop: 2,
      ...fontStyle('regular'),
    },
    txidCard: {
      backgroundColor: theme.colors.surfaceMuted,
      borderRadius: theme.rounded.md,
      padding: 12,
      marginTop: 12,
    },
    partialErrorText: {
      color: theme.isDark ? theme.colors.warning : '#9A3412',
      fontSize: 13,
      lineHeight: 19,
      marginTop: 8,
      ...fontStyle('regular'),
    },
    txidHeader: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
      gap: 8,
    },
    txidLabel: {
      flex: 1,
      minWidth: 0,
      color: theme.colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('semiBold'),
    },
    txidActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginLeft: 'auto',
    },
    txidValue: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    explorerButton: {
      minWidth: 88,
    },
    systemCard: {
      backgroundColor: theme.colors.surfaceRaised,
      borderRadius: theme.rounded.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      marginBottom: theme.spacing.md,
      overflow: 'hidden',
    },
    systemHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    systemTitle: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 22,
      letterSpacing: 0,
      marginLeft: 8,
      ...fontStyle('semiBold'),
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    rowText: {
      flex: 1,
      minWidth: 0,
    },
    rowTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 19,
      letterSpacing: 0,
      ...fontStyle('semiBold'),
    },
    rowSubtitle: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      letterSpacing: 0,
      marginTop: 2,
      ...fontStyle('regular'),
    },
    rowWarningSubtitle: {
      color: theme.isDark ? theme.colors.warning : '#9A3412',
      ...fontStyle('semiBold'),
    },
    rowAmount: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 19,
      marginLeft: 10,
      maxWidth: 120,
      ...fontStyle('semiBold'),
    },
    warningCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: theme.isDark
        ? 'rgba(255, 178, 92, 0.10)'
        : '#FFF7EC',
      borderColor: theme.isDark
        ? 'rgba(255, 178, 92, 0.36)'
        : 'rgba(248, 147, 54, 0.36)',
      borderWidth: StyleSheet.hairlineWidth,
      borderRadius: theme.rounded.lg,
      padding: 14,
      marginBottom: theme.spacing.md,
    },
    warningText: {
      flex: 1,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 19,
      letterSpacing: 0,
      marginLeft: 8,
      ...fontStyle('regular'),
    },
    criticalWarningCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: theme.isDark
        ? 'rgba(255, 107, 117, 0.10)'
        : '#FFF2F3',
      borderColor: theme.isDark
        ? 'rgba(255, 107, 117, 0.38)'
        : 'rgba(242, 45, 55, 0.30)',
      borderWidth: StyleSheet.hairlineWidth,
      borderRadius: theme.rounded.lg,
      padding: 14,
      marginBottom: theme.spacing.md,
    },
    criticalWarningContent: {
      flex: 1,
      minWidth: 0,
      marginLeft: 10,
    },
    criticalWarningTitle: {
      color: theme.isDark ? theme.colors.danger : '#991B1B',
      fontSize: 15,
      lineHeight: 20,
      letterSpacing: 0,
      marginBottom: 6,
      ...fontStyle('semiBold'),
    },
    criticalWarningText: {
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 19,
      letterSpacing: 0,
      ...fontStyle('regular'),
    },
    authorityLineItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.isDark
        ? 'rgba(255, 178, 92, 0.10)'
        : '#FFF7EC',
      borderColor: theme.isDark
        ? 'rgba(255, 178, 92, 0.36)'
        : 'rgba(248, 147, 54, 0.36)',
      borderWidth: StyleSheet.hairlineWidth,
      borderRadius: theme.rounded.sm,
      paddingHorizontal: 8,
      paddingVertical: 7,
      marginTop: 8,
    },
    authorityLineIcon: {
      marginRight: 7,
    },
    authorityLineText: {
      flex: 1,
      minWidth: 0,
    },
    authorityLineLabel: {
      color: theme.isDark ? theme.colors.warning : '#9A3412',
      fontSize: 11,
      lineHeight: 15,
      letterSpacing: 0,
      marginBottom: 1,
      ...fontStyle('semiBold'),
    },
    authorityLineName: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0,
      ...fontStyle('semiBold'),
    },
    infoCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: theme.colors.surfaceMuted,
      borderColor: theme.colors.border,
      borderWidth: StyleSheet.hairlineWidth,
      borderRadius: theme.rounded.lg,
      padding: 14,
      marginBottom: theme.spacing.md,
    },
    infoText: {
      flex: 1,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 19,
      letterSpacing: 0,
      marginLeft: 8,
      ...fontStyle('regular'),
    },
    footer: {
      backgroundColor: theme.colors.background,
      borderTopColor: theme.colors.border,
      borderTopWidth: StyleSheet.hairlineWidth,
      paddingTop: theme.spacing.md,
    },
  });

export default createSpendableKeyRequestInfoStyles;
