import {Platform, StyleSheet} from 'react-native';
import {fontStyle} from '../../globals/fonts';

export const createReceiveListStyles = theme =>
  StyleSheet.create({
    screen: {flex: 1, backgroundColor: theme.colors.background},
    header: {
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: theme.colors.background,
    },
    headerScrolled: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    title: {
      ...theme.typography.headlineMd,
      marginTop: 8,
      marginBottom: 16,
      color: theme.colors.textPrimary,
    },
    list: {paddingBottom: 20},
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 86,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    logo: {marginRight: 16},
    rowBody: {flex: 1, minWidth: 0},
    rowTop: {flexDirection: 'row', alignItems: 'center'},
    assetName: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 17,
      lineHeight: 22,
      ...fontStyle('semiBold'),
    },
    fiat: {
      marginLeft: 12,
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('semiBold'),
    },
    unavailable: {
      marginLeft: 12,
      color: theme.colors.textSubtle,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    crypto: {
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('medium'),
    },
    empty: {alignItems: 'center', paddingHorizontal: 32, paddingTop: 48},
    emptyText: {
      color: theme.colors.textSecondary,
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('regular'),
    },
    skeletonRow: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 86,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
  });

export const createReceiveSheetStyles = theme =>
  StyleSheet.create({
    sheet: {paddingTop: 12},
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    headerSpacer: {width: 34, height: 34},
    sheetTitle: {
      flex: 1,
      color: theme.colors.textPrimary,
      textAlign: 'center',
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('semiBold'),
    },
    close: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
    },
    description: {
      paddingHorizontal: 20,
      paddingBottom: 16,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('regular'),
    },
    list: {paddingHorizontal: 16, paddingBottom: 8},
    group: {marginBottom: 20},
    groupHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      paddingHorizontal: 4,
    },
    groupLogo: {
      width: 28,
      height: 28,
      marginRight: 10,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'visible',
    },
    groupTitle: {
      color: theme.colors.textSubtle,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      ...fontStyle('bold'),
    },
    card: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 62,
      marginBottom: 8,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
    },
    cardName: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 20,
      ...fontStyle('semiBold'),
    },
    balance: {alignItems: 'flex-end', marginRight: 8},
    balanceValue: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 20,
      ...fontStyle('bold'),
    },
    balanceTicker: {
      marginTop: 1,
      color: theme.colors.textSubtle,
      fontSize: 11,
      lineHeight: 14,
      ...fontStyle('regular'),
    },
  });

export const createReceiveDetailsStyles = theme =>
  StyleSheet.create({
    safe: {flex: 1, backgroundColor: theme.colors.background},
    root: {flex: 1},
    scroll: {paddingHorizontal: 20, paddingBottom: 64},
    header: {marginBottom: 24},
    titleRow: {flexDirection: 'row', alignItems: 'center'},
    title: {
      ...theme.typography.headlineMd,
      marginLeft: 12,
      color: theme.colors.textPrimary,
    },
    ticker: {
      marginTop: 4,
      marginLeft: 44,
      color: theme.colors.textSecondary,
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('medium'),
    },
    headerRightButton: {paddingHorizontal: 10, paddingVertical: 8},
    qrWrap: {alignItems: 'center', marginBottom: 24},
    qrSurface: {backgroundColor: '#FFFFFF'},
    networkPill: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 16,
      paddingVertical: 8,
    },
    networkIcons: {flexDirection: 'row', marginRight: 8},
    networkIcon: {
      width: 30,
      height: 30,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'visible',
    },
    moreNetworks: {
      borderRadius: 15,
      backgroundColor: theme.colors.textSecondary,
      overflow: 'hidden',
    },
    moreNetworksText: {
      color: theme.colors.background,
      fontSize: 10,
      ...fontStyle('bold'),
    },
    networkText: {
      marginRight: 4,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('medium'),
    },
    label: {
      marginBottom: 8,
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('semiBold'),
    },
    addressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 16,
      paddingRight: 12,
      paddingVertical: 14,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
    },
    address: {
      flex: 1,
      marginRight: 8,
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('medium'),
    },
    // An absent address is a message rather than a record: normal body copy
    // that wraps instead of identifier type that truncates.
    addressMissing: {
      flex: 1,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('regular'),
    },
    // Raw addresses, hashes and identifiers use the established platform
    // monospace convention. Human VerusID names keep the normal type above.
    identifier: {fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace'},
    cardMeta: {
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    requestCard: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 65,
      marginTop: 16,
      paddingLeft: 20,
      paddingRight: 16,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceRaised,
    },
    requestTitle: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('medium'),
    },
    requestPreview: {
      width: 160,
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    footer: {
      paddingHorizontal: 20,
      paddingTop: 16,
      backgroundColor: theme.colors.background,
    },

    // Terminal page states (missing Asset, no receive-compatible Card,
    // unresolved address). One centred statement and one safe exit.
    stateScreen: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    stateTitle: {
      ...theme.typography.headlineMd,
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    stateBody: {
      marginTop: 10,
      marginBottom: 24,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('regular'),
    },
    stateAction: {width: '100%', maxWidth: 360},

    // Payment-request task. Full-screen stepped composition that mirrors the
    // canonical Gift Card flow: 20-point side inset, 24-point top inset and a
    // 28-point bottom inset inside the fading scroll viewport.
    wizardRoot: {flex: 1, backgroundColor: theme.colors.background},
    wizardViewport: {flex: 1},
    wizardContent: {flexGrow: 1, paddingTop: 24, paddingBottom: 28},
    stepCopy: {marginBottom: 22},
    stepTitle: {color: theme.colors.textPrimary},
    stepHelper: {
      ...theme.typography.bodySm,
      marginBottom: 20,
      color: theme.colors.textSecondary,
    },
    amountRow: {flexDirection: 'row', alignItems: 'center'},
    // The amount is a normal editable field with the shared native decimal
    // keypad; the currency stays beside it so the unit is always visible.
    amountField: {flex: 1, width: 'auto'},
    currency: {
      marginLeft: 8,
      color: theme.colors.textSecondary,
      fontSize: 20,
      lineHeight: 26,
      ...fontStyle('semiBold'),
    },
    estimateWrap: {
      height: 24,
      marginTop: 8,
      justifyContent: 'center',
    },
    estimate: {
      color: theme.colors.textSecondary,
      fontSize: 15,
      lineHeight: 20,
      ...fontStyle('medium'),
    },
    switch: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 20,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: theme.colors.surfaceMuted,
    },
    switchText: {
      marginLeft: 6,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('semiBold'),
    },
    amountError: {marginTop: 12},
    error: {
      marginTop: 12,
      color: theme.colors.danger,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    settingRow: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    settingCopy: {flex: 1, minWidth: 0, paddingRight: 16},
    settingTitle: {
      ...theme.typography.titleRow,
      color: theme.colors.textPrimary,
    },
    settingSubtitle: {
      marginTop: 2,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    slippageField: {marginTop: 20},
    resultWrap: {alignItems: 'center', paddingTop: 4},
    resultQr: {backgroundColor: '#FFFFFF'},
    resultAmount: {
      marginTop: 20,
      color: theme.colors.textPrimary,
      fontSize: 20,
      lineHeight: 26,
      ...fontStyle('semiBold'),
    },
    resultAddress: {
      maxWidth: '100%',
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
  });
