import {StyleSheet} from 'react-native';
import {fontStyle} from '../../globals/fonts';

export const createReceiveListStyles = theme =>
  StyleSheet.create({
    screen: {flex: 1, backgroundColor: theme.colors.background},
    header: {
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: theme.colors.background,
    },
    headerScrolled: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    title: {
      marginTop: 8,
      marginBottom: 16,
      color: theme.colors.textPrimary,
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: -0.2,
      ...fontStyle('bold'),
    },
    search: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'transparent',
      backgroundColor: theme.colors.input,
    },
    searchFocused: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.inputFocused,
    },
    searchInput: {
      flex: 1,
      height: 48,
      paddingHorizontal: 14,
      color: theme.colors.textPrimary,
      fontSize: 15,
      ...fontStyle('regular'),
    },
    list: {paddingBottom: 20},
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 86,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    logo: {marginRight: 16},
    rowBody: {flex: 1, minWidth: 0},
    rowTop: {flexDirection: 'row', alignItems: 'center'},
    assetName: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 17,
      lineHeight: 22,
      ...fontStyle('semiBold'),
    },
    fiat: {
      marginLeft: 12,
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('semiBold'),
    },
    unavailable: {
      marginLeft: 12,
      color: theme.colors.textSubtle,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    crypto: {
      marginTop: 6,
      color: theme.colors.textSecondary,
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('medium'),
    },
    empty: {alignItems: 'center', paddingHorizontal: 32, paddingTop: 48},
    emptyText: {
      color: theme.colors.textSecondary,
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('regular'),
    },
    skeletonRow: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 86,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
  });

export const createReceiveSheetStyles = theme =>
  StyleSheet.create({
    sheet: {paddingTop: 12},
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    headerSpacer: {width: 34, height: 34},
    sheetTitle: {
      flex: 1,
      color: theme.colors.textPrimary,
      textAlign: 'center',
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('semiBold'),
    },
    close: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
    },
    description: {
      paddingHorizontal: 20,
      paddingBottom: 16,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('regular'),
    },
    list: {paddingHorizontal: 16, paddingBottom: 8},
    group: {marginBottom: 20},
    groupHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      paddingHorizontal: 4,
    },
    groupLogo: {
      width: 28,
      height: 28,
      marginRight: 10,
      borderRadius: 6,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
    },
    groupTitle: {
      color: theme.colors.textSubtle,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      ...fontStyle('bold'),
    },
    card: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 62,
      marginBottom: 8,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
    },
    cardName: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 20,
      ...fontStyle('semiBold'),
    },
    balance: {alignItems: 'flex-end', marginRight: 8},
    balanceValue: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 20,
      ...fontStyle('bold'),
    },
    balanceTicker: {
      marginTop: 1,
      color: theme.colors.textSubtle,
      fontSize: 11,
      lineHeight: 14,
      ...fontStyle('regular'),
    },
  });

export const createReceiveDetailsStyles = theme =>
  StyleSheet.create({
    safe: {flex: 1, backgroundColor: theme.colors.background},
    root: {flex: 1},
    scroll: {paddingHorizontal: 20, paddingBottom: 64},
    header: {marginBottom: 24},
    titleRow: {flexDirection: 'row', alignItems: 'center'},
    title: {
      marginLeft: 12,
      color: theme.colors.textPrimary,
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: -0.2,
      ...fontStyle('bold'),
    },
    ticker: {
      marginTop: 4,
      marginLeft: 44,
      color: theme.colors.textSecondary,
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('medium'),
    },
    headerRightButton: {paddingHorizontal: 10, paddingVertical: 8},
    qrWrap: {alignItems: 'center', marginBottom: 24},
    qrSurface: {backgroundColor: '#FFFFFF'},
    networkPill: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 16,
      paddingVertical: 8,
    },
    networkIcons: {flexDirection: 'row', marginRight: 8},
    networkIcon: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 2,
      borderColor: theme.colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    moreNetworks: {backgroundColor: theme.colors.textSecondary},
    moreNetworksText: {
      color: theme.colors.background,
      fontSize: 10,
      ...fontStyle('bold'),
    },
    networkText: {
      marginRight: 4,
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('medium'),
    },
    label: {
      marginBottom: 8,
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('semiBold'),
    },
    addressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 16,
      paddingRight: 12,
      paddingVertical: 14,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
    },
    address: {
      flex: 1,
      marginRight: 8,
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('medium'),
    },
    requestCard: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 65,
      marginTop: 16,
      paddingLeft: 20,
      paddingRight: 16,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceRaised,
    },
    requestTitle: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('medium'),
    },
    requestPreview: {
      width: 160,
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    footer: {
      paddingHorizontal: 20,
      paddingTop: 16,
      backgroundColor: theme.colors.background,
    },
    sheet: {paddingTop: 12},
    sheetBody: {paddingHorizontal: 24, paddingBottom: 24},
    sheetHeading: {
      color: theme.colors.textPrimary,
      fontSize: 28,
      lineHeight: 36,
      ...fontStyle('bold'),
    },
    sheetSubtitle: {
      marginBottom: 20,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('regular'),
    },
    amountStepContent: {
      paddingHorizontal: 24,
      paddingTop: 8,
      paddingBottom: 16,
    },
    amountStepHeading: {
      marginBottom: 16,
      color: theme.colors.textPrimary,
      fontSize: 24,
      lineHeight: 30,
      ...fontStyle('bold'),
    },
    amountRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
    },
    amount: {
      color: theme.colors.textPrimary,
      fontSize: 48,
      lineHeight: 56,
      ...fontStyle('regular'),
    },
    currency: {
      marginLeft: 8,
      color: theme.colors.textSecondary,
      fontSize: 20,
      lineHeight: 26,
      ...fontStyle('semiBold'),
    },
    estimateWrap: {
      height: 24,
      marginTop: 8,
      justifyContent: 'center',
    },
    estimate: {
      color: theme.colors.textSecondary,
      fontSize: 15,
      lineHeight: 20,
      ...fontStyle('medium'),
    },
    switch: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 20,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: theme.colors.surfaceMuted,
    },
    switchText: {
      marginLeft: 6,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('semiBold'),
    },
    keypadWrap: {paddingBottom: 8},
    keypad: {},
    keyRow: {flexDirection: 'row'},
    key: {flex: 1, alignItems: 'center', justifyContent: 'center'},
    keyText: {
      color: theme.colors.textPrimary,
      fontSize: 24,
      lineHeight: 30,
      ...fontStyle('regular'),
    },
    amountError: {marginHorizontal: 24},
    amountStepFooter: {
      paddingHorizontal: 20,
      paddingBottom: 32,
    },
    subjectInput: {
      height: 56,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      color: theme.colors.textPrimary,
      backgroundColor: theme.colors.input,
      fontSize: 16,
      ...fontStyle('regular'),
    },
    subjectFooter: {marginTop: 24, paddingBottom: 8},
    settingsIntro: {marginTop: 8, marginBottom: 24},
    optionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 64,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceMuted,
    },
    optionCopy: {flex: 1, paddingRight: 12},
    optionTitle: {
      flex: 1,
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('semiBold'),
    },
    optionSubtitle: {
      marginTop: 2,
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
      ...fontStyle('regular'),
    },
    slippageLabel: {marginTop: 16, marginBottom: 8},
    slippageInput: {
      height: 44,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      color: theme.colors.textPrimary,
      backgroundColor: theme.colors.input,
      fontSize: 16,
      ...fontStyle('regular'),
    },
    settingsFooter: {marginTop: 16, paddingBottom: 8},
    error: {
      marginTop: 6,
      color: theme.colors.danger,
      fontSize: 12,
      lineHeight: 16,
      ...fontStyle('regular'),
    },
    result: {alignItems: 'center', paddingTop: 16, paddingBottom: 32},
    resultQr: {backgroundColor: '#FFFFFF'},
    resultText: {
      marginTop: 16,
      marginBottom: 16,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      fontSize: 13,
      lineHeight: 20,
      ...fontStyle('medium'),
    },
    resultActions: {width: '80%', marginTop: 8},
    resultButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    resultPrimaryButton: {marginBottom: 12},
    savedResultButton: {opacity: 1},
    resultSecondaryButton: {marginTop: 0},
    supportedChainsBody: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 32,
    },
    supportedChainsDescription: {
      marginBottom: 16,
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      ...fontStyle('regular'),
    },
    networkList: {marginTop: 8, marginBottom: 24},
    networkListItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    networkListText: {marginLeft: 12},
    networkListTitle: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      lineHeight: 22,
      ...fontStyle('semiBold'),
    },
    networkListTicker: {
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      ...fontStyle('regular'),
    },
    loading: {alignItems: 'center', paddingTop: 72, paddingHorizontal: 24},
  });
